import type { Metadata } from "next";
import { Trispace } from "next/font/google";
import "./globals.css";

const trispace = Trispace({
  subsets: ["latin"],
  weight: ["300", "400", "600"],
  variable: "--font-trispace",   // ← add this
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={trispace.variable}>
      <body>{children}</body>
    </html>
  );
}